export const templateConfigs = {
  1: {
    name: "Classic Professional",
    description: "Traditional blue theme",
    primaryColor: "#2b6cb0",
    secondaryColor: "#3182ce",
    accentBg: "#ebf4ff",
    fontFamily: "'Inter', Arial, sans-serif",
    headerAlign: "center",
    sectionBorderStyle: "2px solid #2b6cb0",
    skillBadgeBg: "#ebf4ff",
    skillBadgeColor: "#1a365d",
    nameColor: "#000",
    titleColor: "#000",
    skillsLayout: "grid",
    skillBorderRadius: "4px",
    skillPadding: "6px 10px",
  },
  2: {
    name: "Modern Executive",
    description: "Elegant dark theme",
    primaryColor: "#1a202c",
    secondaryColor: "#2d3748",
    accentBg: "#edf2f7",
    fontFamily: "'Georgia', serif",
    headerAlign: "left",
    sectionBorderStyle: "none",
    sectionUnderline: "3px solid #1a202c",
    skillBadgeBg: "transparent",
    skillBadgeColor: "#1a202c",
    skillBorder: "1px solid #cbd5e0",
    nameColor: "#1a202c",
    titleColor: "#2d3748",
    skillsLayout: "flex",
    skillGap: "16px 10px",
    skillBorderRadius: "20px",
    skillPadding: "8px 16px",
  },
  3: {
    name: "Creative Gradient",
    description: "Vibrant modern design",
    primaryColor: "#ec4899",
    secondaryColor: "#8b5cf6",
    accentBg: "linear-gradient(135deg, #fce7f3 0%, #ede9fe 100%)",
    fontFamily: "'Poppins', 'Segoe UI', sans-serif",
    headerAlign: "center",
    sectionBorderStyle: "none",
    sectionGradient: "linear-gradient(90deg, #ec4899 0%, #8b5cf6 100%)",
    sectionBgGradient: "linear-gradient(135deg, #fdf2f8 0%, #f5f3ff 100%)",
    skillBadgeBg: "linear-gradient(135deg, #f9a8d4 0%, #c4b5fd 100%)",
    skillBadgeColor: "#ffffff",
    nameColor: "#1f2937",
    titleColor: "#6b7280",
    titleBg: "linear-gradient(135deg, #fce7f3 0%, #ede9fe 100%)",
    skillsLayout: "flex",
    skillBorderRadius: "25px",
    skillPadding: "6px 20px",
    skillShadow: "0 4px 6px rgba(139, 92, 246, 0.2)",
  },
};

export const getTemplateStyles = (templateId = 1) => {
  return templateConfigs[templateId] || templateConfigs[1];
};
